# Redirección HTTP → HTTPS
server {
    listen 80;
    server_name 2asi06.100.30.248.5.nip.io;
    return 301 https://$host$request_uri;
}

# HTTPS principal
server {
    listen 443 ssl;
    server_name 2asi06.100.30.248.5.nip.io;
    ssl_certificate /etc/letsencrypt/live/2asi06.100.30.248.5.nip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/2asi06.100.30.248.5.nip.io/privkey.pem;
    root /usr/share/nginx/html;
    index index.php index.html;

    # Frontend
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Backend Node.js
    location /api/ {
        proxy_pass http://backend:3000/;
    }

    # PHP
    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
